#version 450

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include Renderer
#include Simulation
#include SceneCounts
#include Nodes
#include PlantSpecies
#include PlantPrototypes
#include PlantModules
#include SceneNodeConstants

mat4 getModelMatrix(vec3 pos, vec3 rot, float scale) {
    //scale
    mat4 mS = scale * mat4(1.0);
    mS[3][3] = 1.0;
    //rotate
    /*
    mat4 mR = transpose(mat4(
        1.0 - 2.0*rot.y*rot.y - 2.0*rot.z*rot.z, 2.0*rot.x*rot.y - 2.0*rot.w*rot.z, 2.0*rot.x*rot.z + 2.0*rot.w*rot.y, 0.0,
        2.0*rot.x*rot.y + 2.0*rot.w*rot.z, 1.0 - 2.0*rot.x*rot.x - 2.0*rot.z*rot.z, 2.0*rot.y*rot.z - 2.0*rot.w*rot.x, 0.0,
        2.0*rot.x*rot.z - 2.0*rot.w*rot.y, 2.0*rot.y*rot.z + 2.0*rot.w*rot.x, 1.0 - 2.0*rot.x*rot.x - 2.0*rot.y*rot.y, 0.0,
        0.0, 0.0, 0.0, 1.0
    ));
    */
    mat4 mR = transpose(mat4(
        cos(rot.y)*cos(rot.z), -cos(rot.y)*sin(rot.z), sin(rot.y), 0.0,
        cos(rot.z)*sin(rot.x)*sin(rot.y)+cos(rot.x)*sin(rot.z), cos(rot.x)*cos(rot.z)-sin(rot.x)*sin(rot.y)*sin(rot.z), -cos(rot.y)*sin(rot.x), 0.0,
        -cos(rot.x)*cos(rot.z)*sin(rot.y)+sin(rot.x)*sin(rot.z), cos(rot.z)*sin(rot.x)+cos(rot.x)*sin(rot.y)*sin(rot.z), cos(rot.x)*cos(rot.y), 0.0,
        0.0, 0.0, 0.0, 1.0
    ));
    //translate
    mat4 mT = mat4(1.0);
    mT[3] = vec4(pos, 1.0);
    return mT * mR * mS;
}

bool listIndexToBudModel(uint listIndex, uint speciesIndex, uint prototypeIndex, mat4 moduleModel, out mat4 budModel) {
    uint maxChildren = plantSpecies[speciesIndex].maxNodeChildren;
    uint rootIndex = plantPrototypes[prototypeIndex].firstNode;
    uint currIndex = listIndex;

    uint level = 0;
    uint base = 1;
    uint offset = 0;
    while(currIndex > rootIndex) {
        uint child = 0;
        while(currNodes[currNodes[currIndex].parentIndex].childIndices[child] != currIndex
            && child < maxChildren) {
            child++;
        }
        if(child >= currNodes[currNodes[currIndex].parentIndex].numChildren) {
            return false;
        }

        offset += child * base;
        base *= maxChildren;
        level++;

        currIndex = currNodes[currIndex].parentIndex;
    }

    vec3 position = vec3(moduleModel * vec4(0.0, 0.0, 0.0, 1.0));
    vec3 xAxis = normalize(vec3(moduleModel * vec4(1.0, 0.0, 0.0, 0.0)));
    vec3 yAxis = normalize(vec3(moduleModel * vec4(0.0, 1.0, 0.0, 0.0)));
    vec3 zAxis = normalize(vec3(moduleModel * vec4(0.0, 0.0, 1.0, 0.0)));
    float extent = plantSpecies[speciesIndex].maxExtent;

    for(uint l=0; l<level; l++) {
        base /= maxChildren;
        uint child = offset / base;
        offset -= child * base;

        if(child >= currNodes[currIndex].numChildren) {
            return false;
        }
        currIndex = currNodes[currIndex].childIndices[child];

        position += extent * yAxis;
        extent *= plantSpecies[speciesIndex].sizeDecrease[child];
        float theta = plantSpecies[speciesIndex].branchingThetas[child];
        float phi = plantSpecies[speciesIndex].branchingPhis[child];
        float sinTheta = sin(theta);
        if(theta > 0.001) {
            yAxis = normalize(
                cos(phi) * sinTheta * xAxis
                + cos(theta) * yAxis
                + sin(phi) * sinTheta * zAxis
                + plantSpecies[speciesIndex].gravitropism * vec3(0.0, -1.0, 0.0));
            xAxis = normalize(vec3(-yAxis.z, 0.0, yAxis.x));
            zAxis = normalize(cross(xAxis, yAxis));
        } else {
            xAxis = normalize(
                cos(phi) * xAxis
                + sin(phi) * zAxis);
            yAxis = normalize(yAxis + plantSpecies[speciesIndex].gravitropism * vec3(0.0, -1.0, 0.0));
            zAxis = normalize(cross(xAxis, yAxis));
            xAxis = normalize(cross(yAxis, zAxis));
        }
    }

    //switch from branch origin to bud transform
    position += extent * yAxis;

    budModel = mat4(
        vec4(xAxis, 0.0),
        vec4(yAxis, 0.0),
        vec4(zAxis, 0.0),
        vec4(position, 1.0));
    return true;
}

vec3 nodeModelToEulerAngles(mat4 nodeModel) {
    float y = asin(nodeModel[2][0]);
    float x,z;
    if(abs(y) == 0.5 * renderer.pi) {
        z = 0.0;
        x = sign(y) * atan(nodeModel[0][1], nodeModel[1][1]);
    } else {
        x = atan(-nodeModel[2][1], nodeModel[2][2]);
        z = atan(-nodeModel[1][0], nodeModel[0][0]);
    }
    return vec3(x, y, z);
}

/*
vec4 nodeModelToModuleRotation(mat4 nodeModel) {
    float x, y, z;
    float w = 0.5 * sqrt(nodeModel[0][0] + nodeModel[1][1] + nodeModel[2][2] + 1.0);
    if(abs(w) > renderer.epsilon) {
        x = (nodeModel[1][2] - nodeModel[2][1]) / (4.0 * w);
        y = (nodeModel[2][0] - nodeModel[0][2]) / (4.0 * w);
        z = (nodeModel[0][1] - nodeModel[1][0]) / (4.0 * w);
    } else {
        x = sqrt(0.5 * (nodeModel[0][0] + 1.0));
        y = sqrt(0.5 * (nodeModel[1][1] + 1.0));
        z = sqrt(0.5 * (nodeModel[2][2] + 1.0));
    }
    return vec4(x, y, z, w);
}
*/

void main() {
    uint moduleIndex = gl_GlobalInvocationID.x;
    uint moduleOrder = currentIndex;

    if(prevModules[moduleIndex].status > 0 && prevModules[moduleIndex].order == moduleOrder) {
        Module module = prevModules[moduleIndex];

        //conversion from flux to vigor at the root module
        if(module.order == 0) {
            //flux to vigor
            float fluxToVigor = 2.0;
            float maxRootVigor = 30.0;
            module.vigor = min(fluxToVigor * module.vigor, maxRootVigor);
        }

        //pass vigor on to child modules
        float totalFlux = 0.0;
        for(int c=0; c<module.numChildren; c++) {
            if(prevModules[module.childIndices[c]].status > 0) {
                totalFlux += plantPrototypes[module.prototypeIndex].budWeights[c] * prevModules[module.childIndices[c]].vigor;
            }
        }
        for(int c=0; c<module.numChildren; c++) {
            if(prevModules[module.childIndices[c]].status > 0) {
                float weightedFlux = (plantPrototypes[module.prototypeIndex].budWeights[c] * prevModules[module.childIndices[c]].vigor) / totalFlux;
                prevModules[module.childIndices[c]].vigor = weightedFlux * module.vigor;
            }
        }

        if(module.status == 1) {
            //senescence
            if(module.vigor < plantSpecies[module.speciesIndex].minVigor) {
                module.status = 0;
            }

        } else if(module.status == 2 && module.order < currSceneCounts[10]) {
            mat4 moduleModel = getModelMatrix(module.position, module.rotation, 1.0);
            Prototype prototype = plantPrototypes[module.prototypeIndex];

            //add child modules
            mat4 budModel;
            for(uint b=0; b<prototype.numBuds; b++) {
                uint listIndex = prototype.firstNode + prototype.budIndices[b];
                if(listIndexToBudModel(listIndex, module.speciesIndex, module.prototypeIndex, moduleModel, budModel)) {
                    uint addedIndex = atomicAdd(currSceneCounts[7], 1);
                    if(addedIndex < currSceneCounts[8]) {
                        prevModules[addedIndex].position = vec3(budModel * vec4(0.0, 0.0, 0.0, 1.0));
                        //prevModules[addedIndex].rotation = nodeModelToModuleRotation(budModel);
                        prevModules[addedIndex].rotation = nodeModelToEulerAngles(budModel);
                        prevModules[addedIndex].status = 1;
                        prevModules[addedIndex].age = plantSpecies[module.speciesIndex].maxModuleAge * simulation.deltaTime;
                        prevModules[addedIndex].vigor = 1.0;
                        prevModules[addedIndex].numRotChanges = 0;
                        //prevModules[addedIndex].minIntersections = 1000.0;
                        prevModules[addedIndex].order = module.order + 1;
                        prevModules[addedIndex].speciesIndex = module.speciesIndex;
                        prevModules[addedIndex].prototypeIndex = module.prototypeIndex;
                        prevModules[addedIndex].parentIndex = moduleIndex;
                        module.childIndices[module.numChildren] = addedIndex;
                        module.numChildren++;
                    }
                }
            }

            module.status = 3;
        }
        
        prevModules[moduleIndex] = module;
    }
}