#version 450

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include Renderer
#include Simulation
#include Nodes
#include PlantSpecies
#include PlantPrototypes
#include PlantModules
#include VoxelCount
#include VoxelData

/*
bool listIndexToChildModel(uint moduleIndex, uint listIndex, out mat4 nodeModel) {
    uint speciesIndex = prevModules[moduleIndex].speciesIndex;
    uint maxChildren = plantSpecies[speciesIndex].maxNodeChildren;
    uint rootIndex = plantPrototypes[prevModules[moduleIndex].prototypeIndex].firstNode;
    uint currIndex = listIndex;

    uint level = 0;
    uint base = 1;
    uint offset = 0;
    while(currIndex > rootIndex) {
        uint child = 0;
        while(currNodes[currNodes[currIndex].parentIndex].childIndices[child] != currIndex
            && child < maxChildren) {
            child++;
        }
        if(child >= currNodes[currNodes[currIndex].parentIndex].numChildren) {
            return false;
        }

        offset += child * base;
        base *= maxChildren;
        level++;

        currIndex = currNodes[currIndex].parentIndex;
    }

    vec3 position = prevModules[moduleIndex].position;
    vec4 modRot = prevModules[moduleIndex].rotation;
    vec3 xAxis = vec3(
            1.0 - 2.0*modRot.y*modRot.y - 2.0*modRot.z*modRot.z,
            2.0*modRot.x*modRot.y + 2.0*modRot.w*modRot.z,
            2.0*modRot.x*modRot.z - 2.0*modRot.w*modRot.y);
        vec3 yAxis = vec3(
            2.0*modRot.x*modRot.y - 2.0*modRot.w*modRot.z,
            1.0 - 2.0*modRot.x*modRot.x - 2.0*modRot.z*modRot.z,
            2.0*modRot.y*modRot.z + 2.0*modRot.w*modRot.x);
        vec3 zAxis = vec3(
            2.0*modRot.x*modRot.z + 2.0*modRot.w*modRot.y,
            2.0*modRot.y*modRot.z - 2.0*modRot.w*modRot.x,
            1.0 - 2.0*modRot.x*modRot.x - 2.0*modRot.y*modRot.y);
    float extent = plantSpecies[speciesIndex].maxExtent;

    for(uint l=0; l<level; l++) {
        base /= maxChildren;
        uint child = offset / base;
        offset -= child * base;

        if(child >= currNodes[currIndex].numChildren) {
            return false;
        }
        currIndex = currNodes[currIndex].childIndices[child];

        position += extent * yAxis;
        extent *= plantSpecies[speciesIndex].sizeDecrease[child];
        float theta = plantSpecies[speciesIndex].branchingThetas[child];
        float phi = plantSpecies[speciesIndex].branchingPhis[child];
        float sinTheta = sin(theta);
        if(theta > 0.001) {
            yAxis = normalize(
                cos(phi) * sinTheta * xAxis
                + cos(theta) * yAxis
                + sin(phi) * sinTheta * zAxis
                + plantSpecies[speciesIndex].gravitropism * vec3(0.0, -1.0, 0.0));
            xAxis = normalize(vec3(-yAxis.z, 0.0, yAxis.x));
            zAxis = normalize(cross(xAxis, yAxis));
        } else {
            xAxis = normalize(
                cos(phi) * xAxis
                + sin(phi) * zAxis);
            yAxis = normalize(yAxis + plantSpecies[speciesIndex].gravitropism * vec3(0.0, -1.0, 0.0));
            zAxis = normalize(cross(xAxis, yAxis));
            xAxis = normalize(cross(yAxis, zAxis));
        }
    }

    //switch from branch origin to bud transform
    position += extent * yAxis;

    nodeModel = mat4(
        vec4(xAxis, 0.0),
        vec4(yAxis, 0.0),
        vec4(zAxis, 0.0),
        vec4(position, 1.0));
    return true;
}
*/

bool listIndexToBudPos(uint moduleIndex, uint listIndex, out vec3 budPos) {
    uint speciesIndex = prevModules[moduleIndex].speciesIndex;
    uint maxChildren = plantSpecies[speciesIndex].maxNodeChildren;
    uint rootIndex = plantPrototypes[prevModules[moduleIndex].prototypeIndex].firstNode;
    uint currIndex = listIndex;

    uint level = 0;
    uint base = 1;
    uint offset = 0;
    while(currIndex > rootIndex) {
        uint child = 0;
        while(currNodes[currNodes[currIndex].parentIndex].childIndices[child] != currIndex
            && child < maxChildren) {
            child++;
        }
        if(child >= currNodes[currNodes[currIndex].parentIndex].numChildren) {
            return false;
        }

        offset += child * base;
        base *= maxChildren;
        level++;

        currIndex = currNodes[currIndex].parentIndex;
    }

    float nodeAge = prevModules[moduleIndex].age / plantSpecies[speciesIndex].maxNodeAge;
    vec3 xAxis = vec3(1.0, 0.0, 0.0);
    vec3 yAxis = vec3(0.0, 1.0, 0.0);
    vec3 zAxis = vec3(0.0, 0.0, 1.0);
    float extent = plantSpecies[speciesIndex].maxExtent;
    vec3 position = min(nodeAge, 1.0) * extent * yAxis;

    for(uint l=0; l<level; l++) {
        base /= maxChildren;
        uint child = offset / base;
        offset -= child * base;

        if(nodeAge < 1.0 || child >= currNodes[currIndex].numChildren) {
            return false;
        }
        currIndex = currNodes[currIndex].childIndices[child];

        float theta = plantSpecies[speciesIndex].branchingThetas[child];
        float phi = plantSpecies[speciesIndex].branchingPhis[child];
        float sinTheta = sin(theta);
        if(theta > 0.001) {
            yAxis = normalize(
                cos(phi) * sinTheta * xAxis
                + cos(theta) * yAxis
                + sin(phi) * sinTheta * zAxis
                + plantSpecies[speciesIndex].gravitropism * vec3(0.0, -1.0, 0.0));
            xAxis = normalize(vec3(-yAxis.z, 0.0, yAxis.x));
            zAxis = normalize(cross(xAxis, yAxis));
        } else {
            xAxis = normalize(
                cos(phi) * xAxis
                + sin(phi) * zAxis);
            yAxis = normalize(yAxis + plantSpecies[speciesIndex].gravitropism * vec3(0.0, -1.0, 0.0));
            zAxis = normalize(cross(xAxis, yAxis));
            xAxis = normalize(cross(yAxis, zAxis));
        }
        extent *= plantSpecies[speciesIndex].sizeDecrease[child];
        nodeAge = (prevModules[moduleIndex].age - (float(currNodes[currIndex].order) * plantSpecies[speciesIndex].maxNodeAge)) / plantSpecies[speciesIndex].maxNodeAge;
        position += min(nodeAge, 1.0) * extent * yAxis;
    }

    budPos = position;
    return true;
}

void updateBoundingSphere(uint moduleIndex, out vec3 bsCenter, out float bsRadius) {
    uint prototypeIndex = prevModules[moduleIndex].prototypeIndex;
    float relAge = plantSpecies[prevModules[moduleIndex].speciesIndex].maxModuleAge - prevModules[moduleIndex].age;
    vec3 budPos = vec3(0.0);
    vec3 budMin = vec3(0.0);
    vec3 budMax = vec3(0.0);
    for(uint n=0; n<plantPrototypes[prototypeIndex].numNodes; n++) {
        uint listIndex = plantPrototypes[prototypeIndex].firstNode + n;
        if(listIndexToBudPos(moduleIndex, listIndex, budPos)) {
            budMin = min(budMin, budPos);
            budMax = max(budMax, budPos);
        }
    }
    bsCenter = budMin + 0.5 * (budMax - budMin);
    vec3 budDist = bsCenter;
    float maxDistSq = dot(budDist, budDist);
    for(uint n=0; n<plantPrototypes[prototypeIndex].numNodes; n++) {
        uint listIndex = plantPrototypes[prototypeIndex].firstNode + n;
        if(listIndexToBudPos(moduleIndex, listIndex, budPos)) {
            budDist = budPos - bsCenter;
            maxDistSq = max(maxDistSq, dot(budDist, budDist));
        }
    }
    bsRadius = sqrt(maxDistSq);
}

void main() {
    uint moduleIndex = gl_GlobalInvocationID.x;
    Module module = prevModules[moduleIndex];

    if(module.status == 0) {
        //pass deletions on to next frame
        currModules[moduleIndex].status = 0;

    } else {
        if(module.status == 1) {
            updateBoundingSphere(moduleIndex, module.center, module.radius);

            //TO DO: update module orientation
        }
        
        currModules[moduleIndex] = module;
    }
}